![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [7]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [8]:
np.__version__

'2.2.4'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [5]:
my_array = np.arange(10)

print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [49]:
array_3 = np.arange(9).reshape(3,3)

array_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
array_3_bools = array_3 >= 0

array_3_bools

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
array_3 = np.full((5,3), True)

print(array_3)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [6]:
print("Los impares de la my_array es")
print(my_array[my_array % 2 == 1])

Los impares de la my_array es
[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [8]:
nuevo_array = my_array.copy()
nuevo_array[nuevo_array % 2 == 1] = -1
nuevo_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [27]:
impar_my_array = np.where(my_array % 2 == 1,-1, my_array)

print(impar_my_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [58]:
my_array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(a)
print()
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [62]:
np.concatenate((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [65]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(a)
print()
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [68]:
np.concatenate((a,b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [71]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


print("Los elementos en común de las dos listas es:")
comun = np.intersect1d(a,b)
print(comun)

Los elementos en común de las dos listas es:
[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [73]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate(
        (a1, a2, ...),
        axis=0,
        out=None,
        dtype=None,
        casting="same_kind"
    )
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [74]:
my_array = np.arange(10)

print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [77]:
multiplica_my_array = my_array * 10

print(multiplica_my_array)

[ 0 10 20 30 40 50 60 70 80 90]


In [11]:
my_array.dot(10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [79]:
print(my_array[0])

0


In [80]:
print(my_array[-1])

9


In [85]:
print(my_array[1:8])

[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [88]:
my_matrix = np.arange(0,9).reshape(3,3)

my_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [94]:
secuencia = np.arange(1,50,3)

print(secuencia)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [177]:
matriz = np.random.randint(1,100,size=[4,5,3])

print(matriz)

[[[34 34 54]
  [25 37 98]
  [26 22 66]
  [72 10 60]
  [36 31  6]]

 [[22 33 58]
  [71 51 30]
  [14 96 45]
  [19 90  4]
  [74 68 42]]

 [[68 37 86]
  [64 16 60]
  [57 26 49]
  [ 9 30 56]
  [49 95 91]]

 [[32  4 22]
  [37 74  5]
  [56 13 77]
  [14 84 26]
  [43 66 37]]]


## Ejercicio 16
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [14]:
matriz_10_1 = np.arange(0,10,1)
matriz_10_1_bool = matriz_10_1 >= 10
print(matriz_10_1_bool)

[False False False False False False False False False False]


In [160]:
print(matriz_10_1_bool.reshape(2,5))

[[False False False False False]
 [False False False False False]]


## Ejercicio 17
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [161]:
x = np.random.randint(10, 20, size = (5,2,6))

x

array([[[16, 16, 16, 12, 16, 10],
        [11, 10, 11, 16, 16, 11]],

       [[15, 11, 16, 11, 11, 17],
        [15, 17, 15, 11, 14, 11]],

       [[10, 18, 12, 16, 18, 13],
        [10, 12, 10, 11, 14, 13]],

       [[11, 12, 14, 11, 10, 10],
        [12, 12, 14, 11, 17, 16]],

       [[18, 10, 13, 15, 11, 13],
        [13, 17, 12, 10, 19, 15]]], dtype=int32)

In [163]:
print("1. El array tiene", x.size,"elementos.")
print("2.", x.ndim,"dimensiones.")
print("3.", x.shape,"son las longitudes de las dimensiones")

1. El array tiene 60 elementos.
2. 3 dimensiones.
3. (5, 2, 6) son las longitudes de las dimensiones
