![imagen](./img/ejercicios.png)

In [5]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [6]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(my_array[::-2])

[9 7 5 3 1]


In [8]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [9]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [11]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
print(my_array[2::-1])

[2 1 0]


In [13]:
print(sorted(my_array[:3],reverse=True))

[np.int64(2), np.int64(1), np.int64(0)]


In [14]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [15]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [17]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [19]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [20]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [21]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [22]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [23]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [24]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [25]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [26]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [27]:
x == "Loro"

array([ True, False, False,  True, False])

In [28]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [29]:
print(np.where(x== "Loro")[0])

[0 3]


In [30]:
print(np.where(x == "Loro")[0])

[0 3]


In [31]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [32]:
# np.where(x == "Loro", x, np.nan)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [33]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [34]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


In [35]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [36]:
zeros = np.repeat(0,10)
print("Array de 10 0s")
print(zeros)
print("Tamaño en bytes")
print(zeros.nbytes)

Array de 10 0s
[0 0 0 0 0 0 0 0 0 0]
Tamaño en bytes
80


In [47]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
zeros[3] = 1

print(zeros)

[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [38]:
vector1049 = np.arange(10,50,1)

print(vector1049)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [39]:
print(vector1049[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [49]:
print(np.flip(vector1049))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [40]:
vector0 = [1,2,0,0,4,0]
indices = np.nonzero(vector0)[0] 
print(indices)

[0 1 4]


In [52]:
print(np.where(vector0 != 0)[0])

ValueError: Calling nonzero on 0d arrays is not allowed. Use np.atleast_1d(scalar).nonzero() instead. If the context of this error is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [59]:
x = np.random.randint(1, 100, size = (1,10,10))

print(x)

print("Valor máximo: ", x.max())
print("Valor mínimo: ", x.min())

[[[61 82 68 93  3 84 43 43 33 33]
  [74 73 64  4 43 36 73 84 72 91]
  [ 7  7 60 58 15 42 21 81 20 53]
  [40 95  4 27 57 35 32 76 25 30]
  [18  7 54 82 13  5 96 45 12 95]
  [31 32 46 60 67 97 61 26 53 59]
  [24 56 17 97 65 58 72 44 82 22]
  [14 88 56 32 44 40 67 21 73 17]
  [30 24 54 20 59 60 87 12 99 29]
  [11 43 92 12 46 10 94 83  4 78]]]
Valor máximo:  99
Valor mínimo:  3


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [60]:
x = np.random.randint(1, 100, size=(30))

print(x)
print(x.size)
print("La media del vector es", x.mean())

[45 59 91 24 15  8 53 26 73  7 22 75 36 33 74 65 14 23 29 29 31 75 36 31
 48 92 17  8 53 42]
30
La media del vector es 41.13333333333333


In [ ]:
r = np.random.randint(0,6, (1000,1000))

print(r)

print(r.mean())

MemoryError: Unable to allocate 3.64 TiB for an array with shape (1000000, 1000000) and data type int32

In [132]:
print(np.average(r))

2.498885


## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [147]:
x = np.random.randint(1, 100, size = (1,5,5))

print(x)
print(np.average(x))
print("Los valores normalizados son:")
print((x-x.mean())/x.std())


[[[93 87 92 91 95]
  [52  2 13 14 92]
  [17 39 15 68 70]
  [85 74 57 64 24]
  [67 55 79 41 61]]]
57.88
Los valores normalizados son:
[[[ 1.20857557  1.00209911  1.17416283  1.13975008  1.27740106]
  [-0.20234694 -1.92298414 -1.54444395 -1.51003121  1.17416283]
  [-1.40679298 -0.64971261 -1.47561847  0.34825697  0.41708246]
  [ 0.93327362  0.55473343 -0.03028321  0.21060599 -1.16590377]
  [ 0.31384423 -0.0991087   0.72679715 -0.58088712  0.10736776]]]


## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [44]:
x = np.arange(11)

print(x)



[ 0  1  2  3  4  5  6  7  8  9 10]


In [45]:
x_modificado = x.copy() 
x_modificado[(x_modificado >= 3) & (x_modificado <= 8)] = -1

print(x_modificado)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [46]:
x_negado = x.copy()

x_negado[(x_negado >= 3) & (x_modificado <= 8)] *= -1

print(x_negado)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


*Francisco Olivenza Millón*